[package]
name = "example-utils"
version = "0.0.1"
edition = "2018"

[dependencies]
rubble = { path = "../../crates/rubble", default-features = false }
cortex-m = "0.7.2"
log = "0.4.8"
bbqueue = "0.4.1"
